FROM mcr.microsoft.com/playwright:v1.63.0-noble

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src

RUN yarn build

ENV NODE_ENV=production

CMD ["node", "dist/server.js"]